### ISSUE TITLE
CSS takes a while to load

### ISSUE THREAD

**Issue by zachlatta** [hackclub/v2#10]
Not sure what changed, but this is what the website now looks like when loading it:

![recorded](https://user-images.githubusercontent.com/992248/31942328-d39570a6-b879-11e7-9d7f-529e99ca2abd.gif)

I think it'd be much nicer to have the CSS load and then have the Slack profile pictures populate. Or maybe we could generate a spritesheet of the Slack images?

**Comment by lachlanjc** [comment]
Max mentioned this in #6. I think it’s only happening on non-Apple devices? I need to check on BrowserStack.

**Comment by alchzh** [comment]
weird, does Chrome not use Blink on all devices?

also: close as dup?

**Comment by zachlatta** [comment]
Closing as dupe of #6. Apologies.
