### ISSUE TITLE
Fallback for CSS Grid

### ISSUE THREAD

**Issue by sdupouy** [hackclub/v2#11]
Here is a screenshot of the part with lots of photos at the bottom in Edge 40.15063 on Windows 10 :
![image](https://user-images.githubusercontent.com/21321658/31969581-59b35acc-b915-11e7-9071-3aa3566cf93b.png)
In Internet Explorer 11.674 on Windows 10, CSS isn't computed at all (which means all the square photos at the beginning remain even once the page is fully loaded).

**Comment by lachlanjc** [comment]
👍 Thanks!
