### ISSUE TITLE
Header does not scale well on large displays

### ISSUE THREAD

**Issue by pixelyunicorn** [hackclub/v2#13]
Screenshot from a 27" Apple display explains itself:

![image](https://user-images.githubusercontent.com/607807/32033662-c71bdec4-b9db-11e7-95ce-ee684881fa19.png)

This is something javascript can solve, a possible solution is storing the images in an array, and making it generate as many bubbles as necessary to fill the screen.

**Comment by lachlanjc** [comment]
Duplicate of #9. Thanks!
