### ISSUE TITLE
"Apply to Hack Club" button should be centered

### ISSUE THREAD

**Issue by maxwofford** [hackclub/v2#143]
![screenshot from 2018-01-28 05-57-38](https://user-images.githubusercontent.com/5891442/35823152-629a5204-0a63-11e8-91cd-d0372f673e84.png)

Firefox 58

**Comment by maxwofford** [comment]
Firefox 58 on High Sierra after a page refresh:

![screen shot 2018-02-07 at 12 51 45 am](https://user-images.githubusercontent.com/5891442/35906916-1f796e08-0ba1-11e8-90b0-caa1c3fe95ba.png)

**Comment by lachlanjc** [comment]
I tested this on BrowserStack, a recent version of Firefox on High Sierra. Did you clear your cache?
