### ISSUE TITLE
Make Homepage Title Not "404"

### ISSUE THREAD

**Issue by pixelyunicorn** [hackclub/v2#15]
The current page title as seen by people with JS disabled or some search crawlers is "404 – Hack Club"

![image](https://user-images.githubusercontent.com/607807/32035346-92948dd0-b9e6-11e7-84f4-df4fd133ece0.png)

That page title somehow managed to scare away Yahoo (and in proxy Bing + AOL + DuckDuckGo which uses Yahoo as a data source). The homepage flat out disappeared from the search results :O

![image](https://user-images.githubusercontent.com/607807/32035439-3e701a84-b9e7-11e7-93df-1a88a54a1338.png)

**Comment by pixelyunicorn** [comment]
That was fast 👍

**Comment by lachlanjc** [comment]
Thanks a lot, fixed! And it was flashing before the JS initialized on the homepage anyway.

**Comment by pixelyunicorn** [comment]
Cool, I resubmitted the Hack Club homepage thru Bing/Yahoo Webmaster tools so it should show up again hopefully soon :)
