### ISSUE TITLE
Need to click on submit button twice for API request to be made in Cloud9 setup

### ISSUE THREAD

**Issue by zachlatta** [hackclub/v2#210]
How to reproduce:

1. Go to https://hackclub.com/cloud9_setup/ and enter email
2. Click on "Get Invitation" and notice that you need to click it twice before it actually starts submitting

User examples of this issue: https://fsty.io/v/hLyEHUV and https://fsty.io/v/HwN3HnN (must be Hack Club staff to access)

@MaxWofford, @lachlanjc: think one of you could take a look at this?

**Comment by lachlanjc** [comment]
I just tried it, and it sent the invitation on the first tap

**Comment by zachlatta** [comment]
Still having the issue. Think it's a result of clicking "submit" before unfocusing the text field.

![recorded](https://user-images.githubusercontent.com/992248/37778431-8d417b8a-2daf-11e8-88bc-68fbd24fee78.gif)
