### ISSUE TITLE
Improve metadata for search results

### ISSUE THREAD

**Issue by zachlatta** [hackclub/v2#233]
Right now Hack Club is looking pretty weak when compared to the other listings:

<img width="1378" alt="screen shot 2018-03-17 at 13 27 51" src="https://user-images.githubusercontent.com/992248/37559193-15d778c2-29e7-11e8-9d64-0c1853bc11e6.png">

All we really need is a better description. We got sitelinks, which is awesome, but our description is so short you almost ignore our listing entirely.

**Comment by lachlanjc** [comment]
Took a first pass at this with 2d3a656dee8e82b81a0730827c12d1ceb957ff3b. Thoughts?
