### ISSUE TITLE
"slack" Subdomain and /slack_invite Page Does Not Exist or Work

### ISSUE THREAD

**Issue by TheFanatr** [hackclub/v2#266]
The Slack invitation page seems to have dissappeared. Neither the [subdomain](https://slack.hackclub.com) nor the [direct link](https://hackclub.com/slack_invite) seem to work, but in the 404 page, the Slack logo button at the bottom still tries to link to the page; it may have been erroneously deleted. I could not find any traces of it in my attempt to find it in the site's source.

**Comment by TheFanatr** [comment]
It should also be noted that the same applies for [hackclub.io](https://slack.hackclub.io)'s Slack subdomain.

**Comment by merelinguist** [comment]
@lachlanjc is rewriting it in #260. It looks like it should be ready soon :)

**Comment by TheFanatr** [comment]
For anyone wanting to sign up for a Hack Club Slack account in the meantime, [this](https://deploy-preview-215--hackclub.netlify.com/slack_invite) can be used.

**Comment by lachlanjc** [comment]
That form isn’t working yet, that’s why it’s not live :)

Not sure what the problem is here, the redirect is still live on the main site. In any case, the old form works! https://legacy.hackclub.com/slack_invite

**Comment by TheFanatr** [comment]
I was unaware of the legacy subdomain. I was just using a link that a friend sent (slack.hackclub.com) and found that it did not work. Maybe for now, navigating to slack.hackclub.com or hackclub.com/slack_invite should redirect to the legacy version. Currently, every time I tested the aforementioned URLs, I got a 404.

**Comment by maxwofford** [comment]
@TheFanatr: I'll see what I can do to fix this on the current pages, but I'm having trouble reproducing the error. Can you send me your browser + version?

**Comment by lachlanjc** [comment]
@MaxWofford the new page can’t go live until the API endpoint is, but it’s otherwise ready

**Comment by maxwofford** [comment]
It sounds like it could be a while before the API endpoint goes live so I'd like to make a patch to fix what's currently live. It'd look bad if I told a club leader / member to join the Slack and they end up at a 404 page

**Comment by lachlanjc** [comment]
Totally agreed. But I can't reproduce this—clicking the footer link or going right to https://hackclub.com/slack_invite, the legacy form pops up as expected

**Comment by TheFanatr** [comment]
I believe this is a browser-configuration-related issue, specifically with Firefox Quantum 59.0.2 (64-bit). On the exact same network, I got the links to work on both the latest version of Google Chrome and the iOS 10.3.3 Safari 10 (32-bit), but on firefox, I recieved a 404 error. The weird part is that it only happens to certain installs of Firefox, not including a fresh install.

This is the best console output I could retrieve:

    Loading failed for the <script> with source “https://www.fullstory.com/s/fs.js”.                                                slack_invite:1
    Loading failed for the <script> with source “https://hackclub.com/component---src-pages-404-js-74cb32eef5f1d3e9786d.js”.        slack_invite:1
    Loading failed for the <script> with source “https://hackclub.com/path---404-html-a0e39f21c11f6a62c5ab.js”.                     slack_invite:1
    bundle loading error true                                                                                                       404-html.json:6

**Comment by TheFanatr** [comment]
From some extra research, it would seem that Firefox sometimes has issues with addon scripts that modify content on the page or search for certain content immediately. In my case, the addon causing issues was BitDefender, but apparently things like AdBlock and uBlock also cause the issue.

**Comment by TheFanatr** [comment]
So it may be a good idea to include an extra message on the 404 page, such as "try disabling your ad blocker or other addons that modify the page, then attempt to load the original URL again", if the user is on Firefox.

**Comment by maxwofford** [comment]
@TheFanatr: Thanks for the details. Just tested it out and had a similar issue -- the Slack icon in the footer gets stuck while redirecting and eventually 404s.
