### ISSUE TITLE
Site Doesn't Scroll to Top

### ISSUE THREAD

**Issue by cravend** [hackclub/v2#30]
When you click on the team page, then go back to the homepage, it doesn't scroll you to the top (or bottom).

[![Screenshot from Gyazo](https://gyazo.com/2065ff50e3c2edceaa8bddbc6856e158/raw)](https://gyazo.com/2065ff50e3c2edceaa8bddbc6856e158)

**Comment by itsmingjie** [comment]
Re-referencing this issue on the following page clicks also: 
<img width="782" alt="image" src="https://user-images.githubusercontent.com/13333578/34755107-f90d7f88-f58f-11e7-9855-57fb377be3d3.png">

After clicking... It loads the bottom of the page...
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/13333578/34755118-0a89050c-f590-11e7-99d7-3900cae21f20.png">

**Comment by lachlanjc** [comment]
Fixed with the Gatsby site.
