### ISSUE TITLE
Clubs can only be started ASAP

### ISSUE THREAD

**Issue by maxwofford** [hackclub/v2#32]
You can test this out on https://hackclub.com/apply:

![recorded](https://user-images.githubusercontent.com/5891442/32900708-f74c9d54-caa2-11e7-9695-710632929e2d.gif)

**Comment by maxwofford** [comment]
@lachlanjc Any updates on this?

**Comment by maxwofford** [comment]
@lachlanjc I still have this issue after 9f9d53d

**Comment by lachlanjc** [comment]
@MaxWofford Hmm, I just went to the live website in Safari 11 on macOS and Safari on my iPhone and both select menus are working for me

**Comment by maxwofford** [comment]
Looks like it was cached -- it's working for me now
