### ISSUE TITLE
Philosophy page broken in Chrome

### ISSUE THREAD

**Issue by hedayatnia** [hackclub/v2#348]
![screen shot 2018-06-05 at 7 24 59 pm](https://user-images.githubusercontent.com/2019269/41012443-5f50811c-68f6-11e8-9ec3-d68ae683d84b.png)
![screen shot 2018-06-05 at 7 25 57 pm](https://user-images.githubusercontent.com/2019269/41012445-614df076-68f6-11e8-8946-2e4564dff05e.png)
See screenshots - the line on the fold by "philosophy" is showing up weird in Chrome on Mac.

**Comment by maxwofford** [comment]
Also getting this on Chrome. @lachlanjc: can you take this?

**Comment by merelinguist** [comment]
<img width="374" alt="screenshot 2019-01-06 at 16 12 30" src="https://user-images.githubusercontent.com/24858006/50738617-e46fa280-11cd-11e9-9bce-54533cc99e2b.png">

@hedayatnia @MaxWofford @lachlanjc No longer broken in latest version of Chrome.

**Comment by lachlanjc** [comment]
Thanks @merelinguist, this was a bug in Chrome’s CSS rendering
