### ISSUE TITLE
Gatsby v.2

### ISSUE THREAD

**Issue by merelinguist** [hackclub/v2#361]
Hey all 👋! Would you take a PR to upgrade to Gatsby v.2, or are we waiting for the official release?

cc: @lachlanjc

**Comment by lachlanjc** [comment]
Most certainly, @merelinguist! I’ve already started looking into upgrading to the beta for our projects but if you want to get started on that, it’d be awesome.

**Comment by merelinguist** [comment]
Awesome! I’ll give it a go soon.
