### ISSUE TITLE
404 page crashes when loaded from non-existent page

### ISSUE THREAD

**Issue by alchzh** [hackclub/v2#397]
![2018-08-22-183246_1174x746_scrot](https://user-images.githubusercontent.com/8976828/44497921-ecc5a780-a649-11e8-9b18-38f82d7ee808.png)

`t` is `theme`. Does not occur when accessing http://hackclub.com/404.html .

**Comment by zachlatta** [comment]
![macsie_firefox_61 0](https://user-images.githubusercontent.com/992248/44500785-2d6bf380-a63f-11e8-87b5-3f58a79f88f3.jpg)

Can't repro on Sierre w/ Firefox 61 & uBlock Origin installed. Which OS and browser version do you have? Any other addons that might be messing with stuff?

Do you still run into the issue in a private window w/o cache? Wonder if it's a caching issue.

**Comment by alchzh** [comment]
I think the problem is that I'm not redirecting to `404.html` properly, I'll look into it...

Edit: I got the same error using qutebrowser (WebEngine based) with no modifications. Checking if system settings might be messing it up?

**Comment by zachlatta** [comment]
Yup, can repro on that. Here's what I was able to do (cc @lachlanjc).

1. Open new Firefox 61 on Sierra through BrowserStack
2. Install uBlock Origin addon (Raymond Hill version)
3. Go to https://hackclub.com/notarealpage

**Comment by joshkmartinez** [comment]
This happens on Chrome too with ublock origin. 
<img width="962" alt="screen shot 2018-08-26 at 2 01 48 pm" src="https://user-images.githubusercontent.com/29747003/44633198-7ae8a900-a93c-11e8-9177-5d4bd2301ad8.png">

**Comment by MatthewStanciu** [comment]
This happens for me on everything I try to access it on, including Chrome and Firefox with and without uBlock Origin, and on my iPhone. I don't think it's directly related to uBlock Origin or Firefox. The only difference I see is that on Chrome the error says "3" is undefined, but on Firefox it says "t.space" is undefined.

**Comment by joshkmartinez** [comment]
Its this line in the Nav.js component that's throwing the error for all of us: `padding-left: ${({ theme }) => theme.space[3]}px;` (line 36)

**Comment by maxwofford** [comment]
The page works fine for me (think this may have been fixed in one of @lachlanjc's recent updates). Closing, but comment here if you see it again
