### ISSUE TITLE
Map area is 32px wider than available browser space, leads to scrollbar

### ISSUE THREAD

**Issue by alchzh** [hackclub/v2#4]
![2017-10-23-172811_1366x768_scrot](https://user-images.githubusercontent.com/8976828/31914150-914b1c26-b817-11e7-94ff-c0e707f274be.png)

Browser width is only 1315px across

Chromium 62, Arch Linux

**Comment by lachlanjc** [comment]
With the static map (90004d1de783fdb71029937a87757809b342f5f3), are you still seeing this problem?
