### ISSUE TITLE
Same profile picture shown multiple times

### ISSUE THREAD

**Issue by ifvictr** [hackclub/v2#45]
![2017-12-19_18-59-39-255](https://user-images.githubusercontent.com/10110245/34189181-2de4374e-e4ef-11e7-83a8-dcd76fd260f3.png)

**Comment by lachlanjc** [comment]
Yep, all of them are there twice, scrambled randomly. It was a hack to get the site out the door that hasn't been a priority to redo. Will be fixed with a rewrite of the whole Bubbles system with #9.
