### ISSUE TITLE
Holiday Challenge Leaderboard can be hacked

### ISSUE THREAD

**Issue by itaditya** [hackclub/v2#457]
Hi, there is a way for anyone to get the most number of upvotes and win the challenge. It's based on a simple Gmail feature in which I can create infinite number of unique email ids but the mails sent to any of them is forwarded to mine.

Suppose if you have an email id `xyz@gmail.com` then if anyone mails something to the emails `xyz+1@gmail.com`, `xyz+2@gmail.com` or `xyz+putanythinghere@gmail.com` the emails are forwarded to `xyz@gmail.com` only.

**Steps for hacking the leaderboard-**
1. Register with the email `xyz+1@gmail.com`.
1. Copy the login code sent to `xyz+1@gmail.com`.
1. Paste the code in the challenge form and submit it.
1. Now getting logged in, upvote any submission.
1. Clear the browser cookies and other data from DevTools.
1. Reload the page.
1. Now register with the email `xyz+2@gmail.com` and repeat the process.

To give a submission 30 upvotes, this process has to be repeated thirty times.

**Comment by zachlatta** [comment]
Hey, thanks for the heads up here. We have a shadowbanning system in place and are monitoring votes / submissions :-).

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by zachlatta** [comment]
+@lachlanjc @MaxWofford

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by maxwofford** [comment]
@zachlatta summed it up well – people tried this in previous challenges & we monitor for it now. Going to go ahead and close this for now, please re-open if anything wasn't addressed
