### ISSUE TITLE
Migrate admin tools to separate codebase

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/v2#463]

**Comment by zachlatta** [comment]
Yeah, I think this is the way to go. Probably in form of a Rails app like we did w Bank

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by lachlanjc** [comment]
@zachlatta That’s what I suggested, but it seems like for now we need to move the admin pages on our website to a separate JS codebase so I can make big changes to our marketing site without breaking those tools.

**Comment by zachlatta** [comment]
Ah I see. Learning a lot about importance of tight feedback loops... good to know for the future. Not a good idea to have highly iterated on dependencies shared between marketing pages and admin tool pages, especially when you have a small team building a diverse set of tools

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )
