### ISSUE TITLE
Data Mismatch

### ISSUE THREAD

**Issue by itsmingjie** [hackclub/v2#48]
Content Error

![image](https://user-images.githubusercontent.com/13333578/34238358-2a8bdb5c-e5cf-11e7-8133-381e9df59095.png)
![image](https://user-images.githubusercontent.com/13333578/34238365-30be42c6-e5cf-11e7-8bea-f004ce5f0636.png)

The **states** data is not matching on the same page. Need to update to the latest data.

**Comment by zachlatta** [comment]
Thanks for this. Fixing ASAP.

**Comment by zachlatta** [comment]
Just fixed. Thanks again for this.
