### ISSUE TITLE
The website's title tag is blank in production

### ISSUE THREAD

**Issue by maxwofford** [hackclub/v2#5]
![screenshot_2017-10-23_16 13 38](https://user-images.githubusercontent.com/5891442/31917597-2b53dfc0-b80d-11e7-87ab-105c57d4d314.png)

Chrome 60, Ubuntu 16.04 LTS

**Comment by alchzh** [comment]
Helmet is messing something up

![2017-10-23-193945_1021x248_scrot](https://user-images.githubusercontent.com/8976828/31918299-f3de1ade-b829-11e7-96a1-a69cfef04fb9.png)

See the first title?
