### ISSUE TITLE
Fix SSL issue in old browsers

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/v2#530]
In very old browsers (like IE 8 in XP), hackclub.com does not load whatsoever due to an SSL error.

**Comment by thesephist** [comment]
What's the SSL error? Is there a decent way to reproduce the issue?

My gut feeling is that these browsers are themselves the issue, and a practical solution probably requires weakening security. But I don't really understand the root cause here.

**Comment by lachlanjc** [comment]
Yep. Reproduce by going to hackclub.com in IE6, etc. This is definitely a top reason we don’t have more clubs in areas like West Philly, because the school computers can’t access any of our resources.

**Comment by thesephist** [comment]
How does one run IE6 😂 I have two Windows 10 computers and a mac.....

any idea what the specific error is?

**Comment by lachlanjc** [comment]
Ah, we have a subscription to Browserstack—check the 1Password, I think?

The site just refuses to load at all because of an SSL error.

**Comment by lachlanjc** [comment]
Closing this as we have no intention to fix. I believe modern SSL is just incompatible with old browsers/setups. Feel free to reopen if we do more research/more comes to light here.
