### ISSUE TITLE
Fix Helmet error

### ISSUE THREAD

**Issue by merelinguist** [hackclub/v2#533]
The old service worker patch is causing this error:

```
VM327:1 Uncaught SyntaxError: Unexpected identifier
    at HelmetUtils.js:380
    at Array.forEach (<anonymous>)
    at updateTags (HelmetUtils.js:379)
    at commitTagChanges (HelmetUtils.js:255)
    at HelmetUtils.js:222
```

- [ ] Remove old service worker remover
- [ ] Add updated gatsby offline package (which should be more reliable)

**Comment by lachlanjc** [comment]
This issue got fixed at some point, likely with a dependency upgrade
