### ISSUE TITLE
Hack Club Bank FAQ

### ISSUE THREAD

**Issue by thesephist** [hackclub/v2#581]
This is a tracking issue for a "FAQ" page about Hack Club Bank. If you're using Hack Club Bank, please comment in the thread with questions that you think would be helpful to other organizers if it were included in the FAQ!

- Questions that school admins might ask, about fiscal sponsorship
  - "Are you a teacher or an administrator? Call XXX"
- Simple answer to question, "What is fiscal sponsorship?"
- What happens when Hack Club becomes financially insolvent / if Hack Club wants to act in bad faith?
- How to take advantage of our various partnerships with GitHub, etc.
- What's Hack Club Bank's Tax ID / EIN, and what is it for?
- What happens if I lose my Hack Club Bank card or it's stolen?
- Benevity
- What if I want to stop using Hack Club Bank for my event / organization? Can I leave when I want to?
- I want to run my team on Hack Club Bank, but I'm not a hackathon or Hack Club. What kinds of events do you accept?

**Comment by zachlatta** [comment]
How do I help donors include tax receipts in their end of year tax returns?

--
Zach Latta
Founder, Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by zachlatta** [comment]
My sponsor wants us to use Benevity / Bill.com / some other—potentially internal—supplier management system.

--
Zach Latta
Founder, Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by lachlanjc** [comment]
Thanks, I didn’t want to close this but didn’t seem like the place for this right now

**Comment by thesephist** [comment]
Oh it's implemented already, just in Bank's codebase not here. Hence, closed.
