### ISSUE TITLE
Website looks weird while loading

### ISSUE THREAD

**Issue by maxwofford** [hackclub/v2#6]
![loading](https://user-images.githubusercontent.com/5891442/31926068-681cfe1c-b841-11e7-89ff-7ff6c7a6c107.gif)

**Comment by maxwofford** [comment]
This is on a connection with 180 Mb/s down

**Comment by lachlanjc** [comment]
Hmm, I can’t replicate that on any of my Apple devices. I’ll take a look at BrowserStack sometime soon and investigate this

**Comment by alchzh** [comment]
"Apple devices"? Weird, did you try in an engine other than WebKit?

**Comment by lachlanjc** [comment]
I *think* this is fixed. Could you check again @MaxWofford?

**Comment by maxwofford** [comment]
Yep! Loads great now

**Comment by lachlanjc** [comment]
🙏
