### ISSUE TITLE
Explain what "transacted" counts in Bank stats

### ISSUE THREAD

**Issue by thesephist** [hackclub/v2#608]
<img width="848" alt="Screen Shot 2020-01-06 at 20 50 49" src="https://user-images.githubusercontent.com/5403917/71861998-46573680-30c6-11ea-8cb6-eff88747e824.png">

**Comment by iamcpdev** [comment]
Any updates on this? I can take a crack at it. @thesephist

**Comment by zachlatta** [comment]
Oh @iamcpdev, @thesephist is no longer on the team. I’d talk to @maxwofford to get clearance to move forward on this.

**Comment by lachlanjc** [comment]
Closing since not planning to fix before replacing the Bank marketing site.
