### ISSUE TITLE
Bank Timeline discuss a contract whilst features states that bank is no contract

### ISSUE THREAD

**Issue by sampoder** [hackclub/v2#624]
![Screen Shot 2020-05-21 at 8 09 23 PM](https://user-images.githubusercontent.com/39828164/82557865-16a15a80-9b9f-11ea-905c-47af21b56ea3.png)
![Screen Shot 2020-05-21 at 8 09 18 PM](https://user-images.githubusercontent.com/39828164/82557872-1903b480-9b9f-11ea-9a52-5b66a0e1c7c3.png)

**Comment by lachlanjc** [comment]
Thanks for flagging. @maxwofford can you let me know what the timeline should say instead? I’m not fully familiar with this flow

**Comment by maxwofford** [comment]
Thanks @sampoder! Would not have caught this myself

@lachlanjc:
Day 1: Sign up & get first account access so you can order your cards
Day 4: Sign the contract and get invoice + donation access (ability to collect money)

**Comment by lachlanjc** [comment]
Appreciated & resolved!
