### ISSUE TITLE
Have dark/light theme be set by browser theme

### ISSUE THREAD

**Issue by gleich** [hackclub/v2#633]
This allows the theme to be auto-applied based on if you are using dark or light mode. An example of this would be the GitHub favicon and how it changes to be white if your browser is in dark mode.

Below is relevant StackOverflow post that might help:
https://stackoverflow.com/questions/50840168/how-to-detect-if-the-os-is-in-dark-mode-in-browsers

**Comment by lachlanjc** [comment]
Appreciate the suggestion, but not planning to implement this. I think for apps, like Bank, & documents, like Workshops & https://hackclub.com/vip-newsletters/003/ , color modes are great for accessibility & usability. On our marketing pages though, the colors I’m using are a key part of the story I’m telling—if I invert the colors on a section, that has meaning to the content. So expect to see our written content continue to have color modes, while the marketing site typically will not.
