### ISSUE TITLE
Awkward wording on application page

### ISSUE THREAD

**Issue by zachlatta** [hackclub/v2#68]
![screen shot 2018-01-08 at 19 22 30](https://user-images.githubusercontent.com/992248/34703720-51fed962-f4a9-11e7-8202-e9939f6a1750.png)

**How do I fill out the application?**

_**Sit down with your co-leads and fill out the application.**_

---

![image](https://user-images.githubusercontent.com/992248/34703742-78220be6-f4a9-11e7-8321-2ebf9e040073.png)

**Comment by lachlanjc** [comment]
Is this finished @MaxWofford?

**Comment by maxwofford** [comment]
Yep! We just added a link to our new FAQ (which is much better) to the application page.
