### ISSUE TITLE
Transition pages to hackclub/v3

### ISSUE THREAD

**Issue by maxwofford** [hackclub/v2#696]
The following pages are currently served from this codebase, running gatsbyjs:

- [x] https://hackclub.com/santa
- [x] https://hackclub.com/team
- [x] https://hackclub.com/donate
- [x] https://hackclub.com/philosophy
- [x] https://hackclub.com/camp
- [x] https://hackclub.com/bank
- [x] https://hackclub.com/challenge
- [x] https://hackclub.com/cloud9_setup
- [x] https://hackclub.com/redeem_tech_domain
- [x] https://hackclub.com/stickers

We'd love to get them moved over to the hackclub/v3 codebase. Each page can probably be it's own PR-- they don't have to be all moved at once.

**Comment by sampoder** [comment]
I'll do donate + philosophy for now. FYI: Stickers has been moved

**Comment by maxwofford** [comment]
Looks like the deprecated pages are already move over https://github.com/hackclub/v3/blob/6733a3f64a99393671cc7fad15a1b2ab92ff7da2/pages/deprecated/%5Bdeprecated%5D.js#L49-L67

**Comment by exu3** [comment]
I can do /team

pr: hackclub/v3#156

**Comment by bellesea** [comment]
I can do /santa

**Comment by exu3** [comment]
@sampoder which pages still need to be done?

**Comment by sampoder** [comment]
`/camp` & `/bank`

**Comment by exu3** [comment]
cool, I can take a stab at `/bank`

PR at hackclub/v3#167

**Comment by sampoder** [comment]
that'd be epic

**Comment by sampoder** [comment]
All 10 done, s/o to @eilla1 for all the help!
