### ISSUE TITLE
Half a page of bubbles disappear when coming back

### ISSUE THREAD

**Issue by itsmingjie** [hackclub/v2#88]
![](https://media.giphy.com/media/l0HUakf3HgIdhJX4k/giphy.gif)

See gif, I think it's probably the same issue as #59, where an alternative rendering method should be used to serve content...

** and nope it's not fixed after the merge

**Comment by lachlanjc** [comment]
@mj66 Are you still seeing this issue? I could never reproduce it locally but our CSS rendering process is better now.

**Comment by lachlanjc** [comment]
@mj66 I'm going to close this unless you're still seeing this?
